config/routes.rb
Rails.application.routes.draw do
  resources :dashboards, path: '/', only: [:index, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rate.rb
class Rate < ApplicationRecord
  validates :from_currency, :to_currency, :rate, :date, presence: true
  validates :from_currency, :to_currency, length: { is: 3 }, format: { with: /[A-Z]/ }
  validates :rate, numericality: { only_float: true }
  validate :valid_date

  scope :latest, -> { where(date: Rate.select('MAX(date)')) }
  scope :date_after, ->(date) { where('date > ?', date) if date.present? }
  scope :with_to_currency, ->(to_currency) { where('to_currency = ?', to_currency) if to_currency.present? }
  scope :with_from_currency, ->(from_currency) { where('from_currency = ?', from_currency) if from_currency.present? }

  private

  def valid_date
    errors.add(:date, 'must be a valid date') unless date.is_a?(Date)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :setup_dashboard

  def index
  end

  def create
    if params[:currency_layer_convertor]
      @convertor = CurrencyLayer::Convertor.new(
        to_currency: permitted_params[:to_currency],
        input_number: permitted_params[:input_number]
      )

      if @convertor.valid?
        @convertor.convert!
      end
    end

    if params[:currency_layer_graph]
      @graph = CurrencyLayer::Graph.new(
        to_currency: permitted_graph_params[:to_currency]
      )
      
      if @graph.valid?
        @graph.setup_graph_data!
      end
    end

    respond_to do |format|
      format.html { render action: 'index' }
    end
  end

  private

  def permitted_params
    params.require(:currency_layer_convertor).permit(:to_currency, :input_number)
  end

  def permitted_graph_params
    params.require(:currency_layer_graph).permit(:to_currency)
  end

  def setup_dashboard
    @convertor = CurrencyLayer::Convertor.new
    @graph = CurrencyLayer::Graph.new(to_currency: 'USD')
    @graph.setup_graph_data! unless params[:currency_layer_graph]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
  def base_currency
    StaticData::BASE_CURRENCY
  end

  def to_currencies
    StaticData::TO_CURRENCIES
  end
end

app/views/dashboards/index.html.erb
<h3>Currency Convertor</h3>

<%= render partial: 'shared/form_errors', locals: { object: @convertor } %>

<%= form_for @convertor, url: dashboards_path do |f| %>
  <%= f.label :from_currency, base_currency %>
  <%= f.text_field :input_number %>
  <%= f.label :to_currency %>
  <%= f.select :to_currency, to_currencies  %>
  <%= f.submit :convert %>
<% end %>

<% if @convertor.result.present? %>
  <h3> Result: <%= @convertor.result %> </h3>
<% end %>

<h3>Currency Graph</h3>
<%= render partial: 'shared/form_errors', locals: { object: @graph } %>
<%= form_for @graph, url: dashboards_path do |f| %>
  <span> EUR to </span>
  <%= f.select :to_currency, to_currencies %>
  <%= f.submit :show %>
<% end %>

<%= line_chart(@graph.result, min: 1.05, max: 1.15) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CurrencyConvertor</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_form_errors.html.erb
<% if object.errors.any? %>
  <ul>
    Following errors occured:
    <% object.errors.full_messages.each do |message|%>
      <li><%= message %> </li>
    <%end%>
  </ul>
<%end%>